import { z } from 'zod';
import { uuid } from './primitives';
import { paymentMethodSchema, type PaymentMethod } from './fee.schema';
import { hasAtMostTwoDecimals } from './money-amount';
import { roundRate } from './cash-policy';

/**
 * «تسديد الفواتير المحددة» — one citizen settling several bills in one act.
 * Design: docs/finance.md §3.7.
 *
 * Each bill still gets its own ledger row and its own «RCP-» receipt number, so
 * a reprint, a reversal and the treasury's entries keep working bill by bill.
 * The settlement (`payment_settlements`, 0085) holds what belongs to the whole
 * set: the «BRC-» master number, the notes handed over, the change handed back,
 * and the press's retry key.
 *
 * All or nothing: every bill selected ends PAID, or nothing is written. Notes
 * that do not cover the whole set are refused (`BULK_SETTLE_TENDER_SHORT`); the
 * clerk unticks a bill to pay less.
 */

/** The most bills one press settles. */
export const BULK_SETTLE_MAX_BILLS = 50;

const money = (max: number) =>
  z.coerce
    .number({ invalid_type_error: 'المبلغ يجب أن يكون رقماً' })
    .min(0, 'المبلغ لا يمكن أن يكون سالباً')
    .max(max)
    .refine(hasAtMostTwoDecimals, 'منزلتان عشريتان على الأكثر');

/**
 * The notes handed over, on a cash settlement.
 *
 * `local` is in the municipality's own currency (الإعدادات → العملة الأساسية);
 * `foreign` is in `foreignCurrency`, taken at the municipality's official rate.
 * There is no rate in the request: a settlement of several bills uses the
 * official one, and a different rate for one payment stays a single-bill act
 * (`settlePaymentSchema`), where it is asked for with a reason.
 */
export const bulkTenderSchema = z
  .object({
    // Bounded by the column (DECIMAL(14,2)), so an absurd figure is a 422, not a 500.
    local: money(999_999_999_999).default(0),
    foreign: money(1_000_000_000).default(0),
    foreignCurrency: z.enum(['USD', 'EUR']).default('USD'),
  })
  .superRefine((tender, ctx) => {
    if (tender.local <= 0 && tender.foreign <= 0) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['local'], message: 'أدخل المبلغ المستلم' });
    }
  });

export type BulkTender = z.infer<typeof bulkTenderSchema>;

export const bulkSettlePaymentsSchema = z
  .object({
    /** Whose bills. Every bill must be theirs (`BULK_SETTLE_CITIZEN_MISMATCH`). */
    citizenId: uuid,
    paymentIds: z
      .array(uuid)
      .min(1, 'اختر فاتورة واحدة على الأقل')
      .max(BULK_SETTLE_MAX_BILLS, `لا يمكن تسديد أكثر من ${BULK_SETTLE_MAX_BILLS} فاتورة دفعة واحدة`)
      .refine((ids) => new Set(ids).size === ids.length, 'فاتورة مكرّرة في القائمة'),
    method: paymentMethodSchema,
    /** The محصّل who took the money. Required for COLLECTOR, refused otherwise. */
    collectedById: uuid.optional(),
    /** The Whish transfer's own number. Required for WHISH_MONEY, refused otherwise. */
    whishTransactionRef: z.string().trim().min(4, 'رقم العملية قصير جداً').max(80).optional(),
    /** The notes handed over. Required for CASH, refused otherwise. */
    tendered: bulkTenderSchema.optional(),
    note: z.string().trim().max(500).optional(),
    /**
     * One id per press of «تسديد», generated by the dialog. A retry after a lost
     * response sends the same id and gets the first settlement back.
     */
    clientRequestId: uuid,
  })
  .superRefine((data, ctx) => {
    if (data.method === 'CASH' && !data.tendered) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['tendered'], message: 'أدخل المبلغ المستلم' });
    }
    if (data.method !== 'CASH' && data.tendered) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['tendered'],
        message: 'الدفع بعملتين متاح للدفع النقدي فقط',
      });
    }
    if (data.method === 'COLLECTOR' && !data.collectedById) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['collectedById'],
        message: 'اختر المحصّل الذي استلم المبلغ',
      });
    }
    if (data.method !== 'COLLECTOR' && data.collectedById) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['collectedById'], message: 'المحصّل للتحصيل الميداني فقط' });
    }
    if (data.method === 'WHISH_MONEY' && !data.whishTransactionRef) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['whishTransactionRef'],
        message: 'أدخل رقم عملية التحويل',
      });
    }
    if (data.method !== 'WHISH_MONEY' && data.whishTransactionRef) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['whishTransactionRef'],
        message: 'رقم العملية لتحويل Whish فقط',
      });
    }
  });

export type BulkSettlePayments = z.infer<typeof bulkSettlePaymentsSchema>;

// ──────────────────────────────  the plan  ──────────────────────────────

/** One bill as the plan needs it: what is still owed on it, and in what. */
export interface BulkBill {
  id: string;
  currency: string;
  /** `amount − paidAmount`, read under the bill's lock on the server. */
  outstanding: number;
  /** The order key: oldest first, by due date, then by when it was raised. */
  dueDate: string | Date;
  createdAt: string | Date;
}

/** One ledger row the settlement will write. */
export interface BulkRow {
  paymentId: string;
  currency: string;
  /**
   * What the ledger is asked to record against this bill. On a row with notes
   * it is what they are worth (`local + foreign × rate`); the ledger keeps the
   * outstanding balance as the credit and the rest as change.
   */
  amount: number;
  /** The notes on this row, or null when the row is paid as a plain sum. */
  tender: { local: number; foreign: number; foreignCurrency: string } | null;
  /** The change this row records, in its own currency: `amount − outstanding`. */
  changeGiven: number;
}

export type BulkRefusal =
  | { code: 'BULK_SETTLE_TENDER_SHORT'; params: { shortBy: number; currency: string } }
  | { code: 'BULK_SETTLE_TENDER_EXCEEDS'; params: { amount: number; due: number; currency: string } }
  | { code: 'BULK_SETTLE_CURRENCY_UNSUPPORTED'; params: { currency: string } }
  | { code: 'BULK_SETTLE_RATE_NOT_SET'; params?: undefined };

export interface BulkPlan {
  /** In settlement order: oldest bill first. */
  rows: BulkRow[];
  /** What the selected bills still owe, per currency. */
  due: Record<string, number>;
  /**
   * What is handed back to the citizen, in the municipality's own currency —
   * the figure the receipt prints and the clerk counts out. 0 when the notes
   * were exact, and on every method but CASH.
   */
  change: number;
  /** The rate the foreign notes were taken at, or null when none were needed. */
  exchangeRate: number | null;
}

export type BulkPlanResult = { ok: true; plan: BulkPlan } | { ok: false; refusal: BulkRefusal };

/** Half a pound for ليرة, a tenth of a cent otherwise — the ledger's own tolerance. */
function toleranceFor(currency: string): number {
  return currency === 'LBP' ? 0.5 : 0.001;
}

/** Whole ليرة for ليرة, cents for any other currency — the ledger's own precision. */
function roundIn(value: number, currency: string): number {
  return currency === 'LBP' ? Math.round(value) : Math.round(value * 100) / 100;
}

function time(value: string | Date): number {
  return (value instanceof Date ? value : new Date(value)).getTime();
}

/** Oldest first: by due date, then by when the bill was raised, then by id. */
export function bulkSettlementOrder<T extends Pick<BulkBill, 'id' | 'dueDate' | 'createdAt'>>(bills: T[]): T[] {
  return [...bills].sort(
    (a, b) =>
      time(a.dueDate) - time(b.dueDate) ||
      time(a.createdAt) - time(b.createdAt) ||
      (a.id < b.id ? -1 : a.id > b.id ? 1 : 0),
  );
}

/**
 * How one press's money is spread over the bills it settles. Pure, and run by
 * both apps: the dialog for its live «الباقي للمواطن», the server under the
 * bills' locks, with the balances it read there. The server's answer is the one
 * that is recorded.
 *
 * WHISH_MONEY and COLLECTOR arrive as one sum per bill in the bill's currency:
 * every row is its outstanding balance, with no notes and no change.
 *
 * CASH, with `local` notes in the municipality's currency and `foreign` notes in
 * the second one:
 *
 * 1. A bill in the foreign currency is paid with foreign notes, at face value.
 *    Paying a dollar bill with ليرة would need a rate on a dollar bill, which
 *    the single-bill path does not take either. Too few foreign notes is short.
 * 2. Foreign notes left over go to the bills in the municipality's currency, at
 *    the official rate. ليرة notes above what the ليرة bills owe are refused, as
 *    on a single bill: change comes only from a note too large to split.
 * 3. Those notes all go on **one** row — the newest bill in the municipality's
 *    currency — with its change; every other bill is a plain sum. Splitting a
 *    $20 note across two ليرة bills cannot keep both whole to the cent
 *    (900,000 + 890,000 at 89,500 is $10.06 + $9.94, and the second comes out
 *    370 ل.ل short), so the dollars are never split. When the ليرة notes do not
 *    cover the older bills, the newest bill's change pays them, as a clerk
 *    would do it by hand: one receipt paid with the note, the change handed
 *    back across the counter for the others. Every wallet still moves by what
 *    physically changed hands — +ليرة handed in, +dollars, −change handed back.
 *
 * Every row is then judged again by the ledger, under the bill's own lock.
 */
export function planBulkSettlement(input: {
  bills: BulkBill[];
  method: PaymentMethod;
  tender?: { local: number; foreign: number; foreignCurrency: string } | null;
  /** الإعدادات → العملة الأساسية. */
  baseCurrency: string;
  /** The official rate: base currency per one unit of `tender.foreignCurrency`, or null. */
  exchangeRate: number | null;
}): BulkPlanResult {
  const bills = bulkSettlementOrder(input.bills);
  const due: Record<string, number> = {};
  for (const bill of bills) {
    due[bill.currency] = roundIn((due[bill.currency] ?? 0) + bill.outstanding, bill.currency);
  }

  const plain = (bill: BulkBill): BulkRow => ({
    paymentId: bill.id,
    currency: bill.currency,
    amount: bill.outstanding,
    tender: null,
    changeGiven: 0,
  });

  if (input.method !== 'CASH' || !input.tender) {
    return { ok: true, plan: { rows: bills.map(plain), due, change: 0, exchangeRate: null } };
  }

  const base = input.baseCurrency;
  const foreignCurrency = input.tender.foreignCurrency;
  const local = input.tender.local;
  const foreign = input.tender.foreign;

  const odd = bills.find((bill) => bill.currency !== base && bill.currency !== foreignCurrency);
  if (odd) {
    return { ok: false, refusal: { code: 'BULK_SETTLE_CURRENCY_UNSUPPORTED', params: { currency: odd.currency } } };
  }

  const baseBills = bills.filter((bill) => bill.currency === base);
  const foreignDue = foreignCurrency === base ? 0 : (due[foreignCurrency] ?? 0);
  const baseDue = due[base] ?? 0;

  // 1. The foreign bills, at face value.
  if (foreign < foreignDue - toleranceFor(foreignCurrency)) {
    return {
      ok: false,
      refusal: {
        code: 'BULK_SETTLE_TENDER_SHORT',
        params: { shortBy: roundIn(foreignDue - foreign, foreignCurrency), currency: foreignCurrency },
      },
    };
  }
  const spare = Math.max(0, roundIn(foreign - foreignDue, foreignCurrency));

  // 2. What is left for the bills in the municipality's currency.
  if (baseBills.length === 0) {
    if (spare > 0) {
      return {
        ok: false,
        refusal: {
          code: 'BULK_SETTLE_TENDER_EXCEEDS',
          params: { amount: foreign, due: foreignDue, currency: foreignCurrency },
        },
      };
    }
    if (local > 0) {
      return { ok: false, refusal: { code: 'BULK_SETTLE_TENDER_EXCEEDS', params: { amount: local, due: 0, currency: base } } };
    }
    return { ok: true, plan: { rows: bills.map(plain), due, change: 0, exchangeRate: null } };
  }
  if (local > baseDue + toleranceFor(base)) {
    return { ok: false, refusal: { code: 'BULK_SETTLE_TENDER_EXCEEDS', params: { amount: local, due: baseDue, currency: base } } };
  }
  // Kept to four places, as the ledger stores it, so the row reproduces its own amount (`toTender`).
  const rate = spare > 0 && input.exchangeRate ? roundRate(input.exchangeRate) : null;
  if (spare > 0 && (!rate || rate <= 0)) {
    return { ok: false, refusal: { code: 'BULK_SETTLE_RATE_NOT_SET' } };
  }
  const worth = local + spare * (rate ?? 0);
  if (worth < baseDue - toleranceFor(base)) {
    return {
      ok: false,
      refusal: { code: 'BULK_SETTLE_TENDER_SHORT', params: { shortBy: roundIn(baseDue - worth, base), currency: base } },
    };
  }

  if (spare === 0) {
    // Exact notes in each currency: every bill is a plain sum, and nothing is handed back.
    return { ok: true, plan: { rows: bills.map(plain), due, change: 0, exchangeRate: null } };
  }

  // 3. The foreign notes, all on the newest bill in the municipality's currency.
  const pivot = baseBills[baseBills.length - 1]!;
  const others = roundIn(baseDue - pivot.outstanding, base);
  const pivotLocal = Math.max(0, roundIn(local - others, base));
  const pivotAmount = roundIn(pivotLocal + spare * rate!, base);
  const rows = bills.map((bill): BulkRow =>
    bill.id === pivot.id
      ? {
          paymentId: bill.id,
          currency: bill.currency,
          amount: pivotAmount,
          tender: { local: pivotLocal, foreign: spare, foreignCurrency },
          changeGiven: Math.max(0, roundIn(pivotAmount - bill.outstanding, base)),
        }
      : plain(bill),
  );

  return {
    ok: true,
    plan: { rows, due, change: Math.max(0, roundIn(worth - baseDue, base)), exchangeRate: rate },
  };
}

// ─────────────────────────────  responses  ──────────────────────────────

/** One bill on the consolidated receipt. */
export interface SettlementReceiptItem {
  paymentId: string;
  transactionId: string;
  /** The bill's own receipt, «RCP-…». */
  receiptNumber: string;
  /** «INV-…», or null for a bill raised before migration 0079. */
  invoiceNumber: string | null;
  title: string;
  /** The billing period the bill is for, as stored (`ONCE`, `2026`, `2026-Q3`, …). */
  periodKey: string;
  dueDate: string;
  /**
   * The cadastre parcels and units the bill was assessed on, from its
   * assessment's lines, de-duplicated. Empty for a flat or one-off charge. The
   * screen words them («عقار 123 — شقة»), so the wire stays language-neutral.
   */
  properties: Array<{ propertyNumber: string | null; unitType: string | null; unitCode: string | null }>;
  /** The credit applied to the bill, in its currency. */
  amount: number;
  currency: string;
  /** True once this bill's row has been reversed. */
  reversed: boolean;
}

/** The consolidated receipt, as printed and reprinted. */
export interface SettlementReceipt {
  id: string;
  /** «BRC-2610-0001». */
  number: string;
  occurredAt: string;
  method: PaymentMethod;
  citizen: {
    id: string;
    fullName: string;
    fatherName: string | null;
    phone: string | null;
    whatsapp: string | null;
  };
  collectorName: string | null;
  externalRef: string | null;
  recordedByName: string | null;
  items: SettlementReceiptItem[];
  /** Per currency, what the bills were credited with. */
  totals: Record<string, number>;
  /** CASH only; null otherwise. */
  tender: {
    local: number;
    localCurrency: string;
    foreign: number;
    foreignCurrency: string | null;
    exchangeRate: number | null;
    changeGiven: number;
  } | null;
  /** True when this answers a retry with the settlement already recorded. */
  replayed?: boolean;
}
